FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src

CMD ["python", "-m", "src.history_to_timescale"]
