{
 "title": "Sensori kohtainen näkymä",
 "time": { "from": "2024-08-22T11:02:56.130Z", "to": "2024-08-22T11:45:58.582Z" },
 "templating": {
  "list": [
   {
    "name": "SensorID",
    "query": "SELECT DISTINCT sensor_id\nFROM sensor_data\nORDER BY sensor_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Lämpötilan muutokset",
   "type": "timeseries",
   "description": "Näyttää päivän lämpötilat kellonajan mukaan",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "sensor_data",
     "rawSql": "SELECT\n  timestamp AS time,\n  metric_value::float AS temperature\nFROM sensor_data\nWHERE metric_name = 'temperature'\n  AND sensor_id = '$SensorID'     \nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Viimeisin lämpötila",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_data",
     "rawSql": "SELECT\n  *,\n  metric_value::float AS temperature_float\nFROM sensor_data\nWHERE metric_name = 'temperature'\n  AND sensor_id = '$SensorID'\nORDER BY timestamp DESC;"
    }
   ]
  },
  {
   "title": "Kosteuden muutokset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "sensor_data",
     "rawSql": "SELECT\n  timestamp AS time,\n  metric_value::float AS humidity\nFROM sensor_data\nWHERE metric_name = 'humidity'\n  AND sensor_id = '$SensorID'     \nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Kosteus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_data",
     "rawSql": "SELECT\n  timestamp AS time,\n  metric_value::float AS humidity\nFROM sensor_data\nWHERE metric_name = 'humidity'\n  AND sensor_id = '$SensorID'     \nORDER BY timestamp;"
    }
   ]
  }
 ]
}